### ISSUE TITLE
Error with Python3.5.3

### ISSUE THREAD

**Issue by PaulJoseph5623** [alessandromaggio/pythonping#29]
Hi Alessandro,
I like your Lib pythonping and would like to use it.
I am working with a Raspberry Pi3+ with raspian and Python 3.5.3
I am getting this Error:
    from enum import IntEnum, auto
ImportError : cannot import name 'auto'
It seams that with python 3.5.3 lib 'enum' doesn't support 'auto',  although you write that pythonping is supported from python3.
Is there any way I can get pythonping to work with python 3.5.3?
best regards
Paul

**Comment by cxrider** [comment]
I see the same problem in Debian stretch and Python 3.5.3.   I managed to work around the above error but ended up with an import problem of IntEnum that I could not resolve.   I hesitate to upgrade to a newer release of python as I think it will add an additional layer of administration and I would rather apply the KISS principle here.   Are we out of luck and forced to upgrade to a newer release of Python?

**Comment by alessandromaggio** [comment]
I believe we have a compatibility problem. I believe we should investigate it, and if we can find an easy way to restore backward compatibility we should do it.
Feel free to add a PR for that.

**Comment by cxrider** [comment]
I am new to github so it might take me a bit to figure out how to open the PR but this seems to be an acceptable fix so far.   I used the example for AutoNumber from the enum.py documentation for Python 3.5 found here:  https://docs.python.org/3.5/library/enum.html

root@logmon:~/src# python -V
Python 3.5.3
root@logmon:~/src# cat pping 
#!/usr/bin/env python

from pythonping import ping
ping ('8.8.8.8')
root@logmon:~/src# pip install pythonping
Collecting pythonping
Installing collected packages: pythonping
Successfully installed pythonping-1.0.5
root@logmon:~/src# md5sum /usr/local/lib/python3.5/dist-packages/pythonping/executor.py pythonping/o/excutor.py 
e02f834c6596ecbf98f4c325e2de4cfb  /usr/local/lib/python3.5/dist-packages/pythonping/executor.py
e02f834c6596ecbf98f4c325e2de4cfb  pythonping/o/excutor.py
root@logmon:~/src# ./pping 
Traceback (most recent call last):
  File "./pping", line 3, in <module>
    from pythonping import ping
  File "/usr/local/lib/python3.5/dist-packages/pythonping/__init__.py", line 2, in <module>
    from . import network, executor, payload_provider
  File "/usr/local/lib/python3.5/dist-packages/pythonping/executor.py", line 5, in <module>
    from enum import IntEnum, auto
ImportError: cannot import name 'auto'
root@logmon:~/src# cp pythonping/n/executor.py /usr/local/lib/python3.5/dist-packages/pythonping
root@logmon:~/src# ./pping 
root@logmon:~/src# diff pythonping/o/excutor.py pythonping/n/executor.py 
5d4
< from enum import IntEnum, auto
7,8c6,14
< from . import icmp
< from . import network
---
> if sys.version_info[1] < 8:
>     from enum import IntEnum, Enum
> 
>     class AutoNumber(Enum):
>         def __new__(cls):
>             value = len(cls.__members__) + 1
>             obj = object.__new__(cls)
>             obj._value = value
>             return obj
9a16,21
>     class SuccessOn(AutoNumber):
>         One = ()
>         Most = ()
>         All = ()
> else:
>     from enum import IntEnum, auto
11,14c23,26
< class SuccessOn(IntEnum):
<     One = auto()
<     Most = auto()
<     All = auto()
---
>     class SuccessOn(IntEnum):
>         One = auto()
>         Most = auto()
>         All = auto()
15a28,29
> from . import icmp
> from . import network
root@logmon:~/src#

**Comment by cxrider** [comment]
Well that sucked as a post... guess I should have previewed it first :-)

Let me see if I can clean it up

**Comment by cxrider** [comment]
I'm new to github so it may take me a while to figure out how to create a new PR, but I think I have a fix.   It's based on the AutoNumber use case from the Python 3.5 documentation on enum.py found here: https://docs.python.org/3.5/library/enum.html

**Comment by cxrider** [comment]
@alessandromaggio I could not figure out how to open the PR under your branch so I forked the branch and uploaded my version of executor.py.      Hopefully you can access/use it.  :-)   I've also attached the file here.
[executor.py.txt](https://github.com/alessandromaggio/pythonping/files/3844158/executor.py.txt)

**Comment by alessandromaggio** [comment]
Thanks @cxrider, I have implemented your code in version 1.0.6.
This version is already released and available for download from PyPI. We can consider this issue solved!
